// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-zKrGynfcmVbMgaZ-HMSpgfWV7gZkrCc',
    appId: '1:608033125499:web:aca5fc1e761fd5e0bc1ede',
    messagingSenderId: '608033125499',
    projectId: 'saakouk-pos',
    authDomain: 'saakouk-pos.firebaseapp.com',
    storageBucket: 'saakouk-pos.firebasestorage.app',
    measurementId: 'G-5BK9JQ8ZGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-Hj5dIG5x0t9dBxzkGu0uRoFAFdKHro',
    appId: '1:608033125499:android:d24afccbb3130865bc1ede',
    messagingSenderId: '608033125499',
    projectId: 'saakouk-pos',
    storageBucket: 'saakouk-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUoHzeQWPOdEEAzWJpd6McUKJLWbBeOgk',
    appId: '1:608033125499:ios:51aad50e46301ee0bc1ede',
    messagingSenderId: '608033125499',
    projectId: 'saakouk-pos',
    storageBucket: 'saakouk-pos.firebasestorage.app',
    iosBundleId: 'com.example.saakouk',
  );
}
